### ISSUE TITLE
Cannot start game with the mod active

### ISSUE THREAD

**Issue by FireFragment** [LoremVIpsum/OpenSimpleFrames#27]
When trying to start the game with the mod, the game crashes. I have just Fabric API and OpenSimpleFrames, nothing else on Minecraft 1.19.3

Platform: Linux

<details>
  <summary>Logs</summary>
<pre>
[18:23:19] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.24
[18:23:19] [main/INFO]: Loading 54 mods:
	- fabric-api 0.76.1+1.19.3
	   |-- fabric-api-base 0.4.21+70be179c85
	   |-- fabric-api-lookup-api-v1 1.6.20+49abcf7e85
	   |-- fabric-biome-api-v1 12.1.2+f1c68e5885
	   |-- fabric-block-api-v1 1.0.5+e022e5d185
	   |-- fabric-blockrenderlayer-v1 1.1.31+928d44d585
	   |-- fabric-client-tags-api-v1 1.0.12+1134c5b885
	   |-- fabric-command-api-v1 1.2.23+f71b366f85
	   |-- fabric-command-api-v2 2.2.2+2961b4a085
	   |-- fabric-commands-v0 0.2.40+df3654b385
	   |-- fabric-containers-v0 0.1.47+df3654b385
	   |-- fabric-content-registries-v0 3.5.3+1d37d50285
	   |-- fabric-convention-tags-v1 1.3.0+521b5c5285
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebe85
	   |-- fabric-data-generation-api-v1 11.3.3+40dc7a9485
	   |-- fabric-dimensions-v1 2.1.42+00a2eb1085
	   |-- fabric-entity-events-v1 1.5.7+b83334a085
	   |-- fabric-events-interaction-v0 0.4.40+3baeb27a85
	   |-- fabric-events-lifecycle-v0 0.2.45+df3654b385
	   |-- fabric-game-rule-api-v1 1.0.30+99f9db8085
	   |-- fabric-item-api-v1 2.1.11+71b8257385
	   |-- fabric-item-group-api-v1 2.1.14+b5470ac785
	   |-- fabric-key-binding-api-v1 1.0.31+bc01e09785
	   |-- fabric-keybindings-v0 0.2.29+df3654b385
	   |-- fabric-lifecycle-events-v1 2.2.10+23a79c8a85
	   |-- fabric-loot-api-v2 1.1.22+75e9821185
	   |-- fabric-loot-tables-v1 1.1.26+9e7660c685
	   |-- fabric-message-api-v1 5.1.0+c85585f885
	   |-- fabric-mining-level-api-v1 2.1.33+49abcf7e85
	   |-- fabric-models-v0 0.3.27+11ba9c3b85
	   |-- fabric-networking-api-v1 1.2.17+4017a8cb85
	   |-- fabric-networking-v0 0.3.34+df3654b385
	   |-- fabric-object-builder-api-v1 5.4.3+eb2a3ba985
	   |-- fabric-particles-v1 1.0.20+f1e4495b85
	   |-- fabric-recipe-api-v1 1.0.1+5176f73d85
	   |-- fabric-registry-sync-v0 2.1.0+f7b4d36485
	   |-- fabric-renderer-api-v1 2.2.2+3a95925a85
	   |-- fabric-renderer-indigo 0.8.0+3a95925a85
	   |-- fabric-renderer-registries-v1 3.2.31+df3654b385
	   |-- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85
	   |-- fabric-rendering-fluids-v1 3.0.18+f1e4495b85
	   |-- fabric-rendering-v0 1.1.34+df3654b385
	   |-- fabric-rendering-v1 1.13.0+ad17775585
	   |-- fabric-resource-conditions-api-v1 2.3.0+e63306e085
	   |-- fabric-resource-loader-v0 0.11.1+b93ffe4d85
	   |-- fabric-screen-api-v1 1.0.41+f1e4495b85
	   |-- fabric-screen-handler-api-v1 1.3.13+99f9db8085
	   |-- fabric-sound-api-v1 1.0.8+75e9821185
	   |-- fabric-transfer-api-v1 2.1.15+ccd377ba85
	   \-- fabric-transitive-access-wideners-v1 2.3.1+40dc7a9485
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.19.3
	- simpleframes 1.0.6
[18:23:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/firefragment/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:23:19] [main/INFO]: Compatibility level set to JAVA_16
[18:23:19] [main/INFO]: Compatibility level set to JAVA_17
[18:23:24] [main/INFO]: Building optimized datafixer
[18:23:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:23:31] [Render thread/INFO]: Setting user: RedQuant
---- Minecraft Crash Report ----
// I'm sorry, Dave.
Time: 2023-11-09 18:23:32
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simpleframes'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoSuchFieldError: field_25105
	at com.loremv.simpleframes.SimpleFrames.<clinit>(SimpleFrames.java:40)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 16 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 6.2.0-36-generic
	Java Version: 17.0.8.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1640148032 bytes (1564 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: CoffeeLake-H GT2 [UHD Graphics 630]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GP106M [GeForce GTX 1060 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1c20
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 7842.76
	Virtual memory used (MB): 7040.83
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.76.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.23+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.2+2961b4a085
			fabric-commands-v0: Fabric Commands (v0) 0.2.40+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.3+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attach
ment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+b93ffe4d85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.24
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		simpleframes: Open Simple Frames 1.0.6
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /mnt/dawin/Users/Public/Minecraft/_multimc/instances/1.19.3/.minecraft/crash-reports/crash-2023-11-09_18.23.32-client.txt
Process exited with code 255.
</pre>

</details>

**Comment by LoremVIpsum** [comment]
I think this is the same thing as #29 basically the way I make creative tabs apparently doesn't exist in newer fabric versions, if you can use an older one, try it, if not I will fix it as soon as I get time :)

**Comment by FireFragment** [comment]
Yes, I'm now using a different version, where it works correctly.

**Comment by BigClarky** [comment]
> Yes, I'm now using a different version, where it works correctly.

FireFragment, Which fabric loader version and api version did you end up using?

**Comment by FireFragment** [comment]
I use Fabric Loader 0.14.24 with Minecraft 1.19.2 and the mod works with that

**Comment by LoremVIpsum** [comment]
this still need to be fixed properly so I will leave this issue open
