### ISSUE TITLE
Crash when trying to set textures from certain blocks

### ISSUE THREAD

**Issue by thehobojoe** [LoremVIpsum/OpenSimpleFrames#3]
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.loremv.simpleframes.utility.FakeryBakery.createFakeStaticBlock(FakeryBakery.java:140)
	at com.loremv.simpleframes.utility.FakeryBakery.createFakeStaticBlock(FakeryBakery.java:130)
	at net.minecraft.class_773.handler$hdd001$getModel(class_773.java:2041)
	at net.minecraft.class_773.method_3335(class_773.java:34)
	at net.minecraft.class_773.method_3339(class_773.java:25)
	at net.minecraft.class_727.<init>(class_727.java:25)
	at net.minecraft.class_702.method_34020(class_702.java:462)
	at net.minecraft.class_265.method_1112(class_265.java:93)
	at net.minecraft.class_244.method_31941(class_244.java:202)
	at net.minecraft.class_251.method_1053(class_251.java:197)
	at net.minecraft.class_265.method_1089(class_265.java:93)
	at net.minecraft.class_702.method_3046(class_702.java:442)
	at net.minecraft.class_638.method_31595(class_638.java:1036)
	at net.minecraft.class_761.method_8567(class_761.java:2938)
	at net.minecraft.class_638.method_8444(class_638.java:591)
	at net.minecraft.class_2248.method_33614(class_2248.java:497)
	at net.minecraft.class_2248.method_9576(class_2248.java:502)
	at net.minecraft.class_636.method_2899(class_636.java:127)
	at net.minecraft.class_636.method_41936(class_636.java:157)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:156)
	at net.minecraft.class_310.method_1536(class_310.java:1685)
	at net.minecraft.class_310.method_1508(class_310.java:1999)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

This occurred when setting the texture of a block from Powah. On reloading the world, the entire chunk that the broken frame was in became corrupted and is invisible, but block outlines can still be seen, so it seems to just be a rendering failure and not a block data one. When trying to break the frame that caused the first crash, the game crashes again with the same error.

https://user-images.githubusercontent.com/3493638/215368731-1f11f54f-8add-47c6-acaa-ebfdfe3b314f.mp4

**Comment by LoremVIpsum** [comment]
this is also hopefully fixed with https://github.com/LoremVIpsum/OpenSimpleFrames/releases/tag/dev2

**Comment by LoremVIpsum** [comment]
please reopen the issue if you believe this bug has persisted
